######################################
# Stages
######################################
stages:
  - Do All

######################################
# Compose Stage
######################################

check_if_mounted:
  stage: Do All
  script:
    - ls -a /lib/modules
check_disk_space:
  stage: Do All
  script:
    - df -h


install-dependencies:
  stage: Do All
  script:
    - dnf update -y
    - dnf install -y just ostree lorax rpm-ostree jq pip selinux-policy selinux-policy-targeted policycoreutils openssl git zstd buildah curl
    - dnf repoquery --requires akmod-spcm4
    - pip install pyyaml
    - df -h
    - just compose photon-pony
    - just lorax photon-pony
  artifacts:
    paths:
      - "iso/Fedora*"
      - "iso/KS-Fedora*" 
