######################################
# Stages
######################################
stages:
  - Do All

######################################
# Compose Stage
######################################

install-dependencies:
  stage: Do All
  script:
    - ls /lib/modules
    - dnf install -y just ostree lorax rpm-ostree jq pip selinux-policy selinux-policy-targeted policycoreutils openssl git zstd buildah
    - pip install pyyaml
    - just compose photon-pony
    - just lorax photon-pony
  artifacts:
    paths:
      - "iso/Fedora*"
      - "iso/KS-Fedora*" 
