######################################
# Stages
######################################

stages:
  - BUILD STAGE

######################################
# BUILD STAGE
######################################
build-ppos:
  stage: BUILD STAGE
  tags:
    - ppos
  script:
    - sudo dnf install -y just ostree lorax rpm-ostree jq pip selinux-policy selinux-policy-targeted policycoreutils openssl git kmodtool
    - pip install --user pyyaml
    - sudo just compose photon-pony
    - sudo just lorax photon-pony
    - openssl x509 -in secureBoot/PK.pem -pubkey -noout > secureBoot/PK_pub.pem
  artifacts:
    paths:
      - "secureBoot/PK_pub.pem"
      - "iso/Fedora*"
      - "iso/KS-Fedora*"
    expire_in:  5 hours
