
######################################
# Stages
######################################
stages:
  - Compose Stage
  - Lorax Stage
######################################
# Dependencie Stage
######################################

compose-build: 
  stage: Dependencie Stage
  script:
    - sudo /usr/bin/just compose photon-pony

lorax-build:
  stage: Lorax Stage
  script:
    - sudo /usr/bin/just lorax photon-pony



  