
######################################
# Stages
######################################
stages:
  - Compose Stage
  - Lorax Stage
  - Artifact Stage

######################################
# Compose Stage
######################################
compose-build: 
  stage: Compose Stage
  script:
    - sudo /usr/bin/just compose photon-pony

######################################
# Lorax Stage
######################################
lorax-build:
  stage: Lorax Stage
  script:
    - sudo /usr/bin/just lorax photon-pony
  needs:
    - compose-build
    
######################################
# Artifact Stage Stage
######################################
#artifact-build:
 # stage: Artifact Stage
  #artifacts:
   # paths:
    #  - "iso/Fedora*"
     # - "iso/KS-Fedora*"
  #needs:
   # - lorax-build




  