
######################################
# Stages
######################################
stages:
  - Compose Stage
  - Lorax Stage

######################################
# Compose Stage
######################################
compose-build: 
  stage: Compose Stage
  script:
    - sudo /usr/bin/just compose photon-pony

######################################
# Lorax Stage
######################################
lorax-build:
  stage: Lorax Stage
  script:
    - sudo /usr/bin/just lorax photon-pony



  